apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::339712954024:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-KUjk3fsWZQRm
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      usearn: arn:aws:iam::339712954024:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-08-09T05:19:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1288"
  uid: 2ffd4b42-d2a5-4de9-9575-83dafa535242
