apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::339712954024:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-SbfgbYSSoQvc
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::339712954024:user/suresh
      username: suresh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::339712954024:user/ramesh
      username: ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::339712954024:user/john
      username: john
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::339712954024:user/rahim
      username: rahim
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-11T01:49:27Z"
  name: aws-auth
  namespace: kube-system
  uid: 6c6ceddf-9413-4206-b8ce-e1ed9a0cac09